### ISSUE TITLE
Get-WikiPage Handling

### ISSUE THREAD

**Issue by lipkau** [brianbunke/ConfluencePS#15]
## Current behavior
Currently there is one function to get pages, one to get child pages and one to get pages by label

## Proposition
Allow `Get-WikiPage` to do all of these by:
```
# Get a page by object (useful, when you have a page object without all properties (eg: $page.ancestors))
Get-WikiPage -inputObject $somePage.ancestors

# Get a page by id
Get-WikiPage -pageID @(1,2,3)

# Get all pages of space
Get-WikiPage -spaceKey "RD"

# Get all pages with title
Get-WikiPage -Title "Home"

# Get a page with title in space
Get-WikiPage -Title "Home" -SpaceKey "RD"

# Get a page and all it's children (works with all inputs above)
$pageObject | Get-WikiPage -Recurse

# Get all pages with label
Get-WikiPage -label "meeting-notes","foo" [-SpaceKey <string>]
```

@brianbunke :
**please let me know what you think**
If you agree, I will make the changes and add them to my refactoring branch

**Comment by brianbunke** [comment]
All of that looks pretty good! I have two questions:

1. Is `-InputObject` just going to be a bunch of `If` statements to check for object properties? It's a pretty generic parameter name, and will be a lot tougher to provide documentation if there are multiple different scenarios.
2. Are you planning on changing the way `-Limit` behaves?

**Comment by lipkau** [comment]
1. Input object is already implemented in my branch.  
It takes the object and uses the props it can take. I have not implemented a validation, as the return of the invoke returns quite nicely... you can use `-ErrorAction` to suppress errors in cases you expect it to happen.
2. Yes. I will implemented pagination on all `Get-*` functions

**Comment by lipkau** [comment]
The `-InputObject` is good for scenarios like
```
(Get-WikiPage -title "servers").Ascendents | Get-WikiPage
```

**Comment by brianbunke** [comment]
👍 👍

**Comment by lipkau** [comment]
I changed my mind regarding `-Recurse`

I will favor `Get-WikiChildPage`, as the behavior will be more similar to up-coming functions (comments and attachments)
