### ISSUE TITLE
Add output type declaration

### ISSUE THREAD

**Issue by lipkau** [brianbunke/ConfluencePS#17]
Some functions lack the `[OutputType()]` declaration

**Comment by brianbunke** [comment]
While this is always best practice, it's not really needed until the custom object types (e.g. `ConfluencePS.Page`) drop in v2.0. As such, I'm labeling this 2.0 as well.

**Comment by lipkau** [comment]
implemented with 620263fa6249b5e7fd2279f902cafab788673ad3
