### ISSUE TITLE
Add base URL parameter?

### ISSUE THREAD

**Issue by lipkau** [brianbunke/ConfluencePS#19]
It is possible to add a mandatory parameter to all functions and set the value through $PSDefaultParameterValues in `Set-WikiInfo`.

This brings the advantage of allowing the user to use a function without **having** to set the wiki info before hand.
Behavior is unchanged if user uses the functions as currently implemented

**Comment by lipkau** [comment]
If we decide to use this, `-Credential` should be done in the same way

**Comment by brianbunke** [comment]
I'm kind of slow. Do you mind posting some code snippets of how this could change user behavior?

**Comment by lipkau** [comment]
No problem... Here would be a script that takes info from one server and uses it on another:
```
$confluenceServer1 = @{
    ApiURi = "https://public.url/wiki"
    Credential = (Get-Credential)
}

$confluenceServer2 = @{
    ApiURi = "https://intranet.url/wiki"
    Credential = (Get-Credential)
}

$serverList = Get-WikiSpace @confluenceServer1 "Servers" | Get-WikiPage @confluenceServer1 -Label "sensitive"

$serverList | New-WikiPage @confluenceServer2

$serverList | Remove-WikiPage @confluenceServer1
```

**Comment by brianbunke** [comment]
Sounds good. When you look into this, is it technically possible (and feasible) to take this example:

```posh
$serverList = Get-WikiSpace @confluenceServer1 "Servers" | Get-WikiPage @confluenceServer1 -Label "sensitive"
```

And have `Get-WikiSpace` pass the specified URI/Creds down the pipe, so they wouldn't need to be specified at each step?

**Comment by lipkau** [comment]
Hm. I will have to look into that.
