### ISSUE TITLE
Extend verbose and debug messages

### ISSUE THREAD

**Issue by lipkau** [brianbunke/ConfluencePS#21]
I like to declare the entry and exit point of functions in the verbose.
I also like to prefix all verbose and debug msgs with the current function name.
E.g.: https://github.com/lipkau/PsIni/blob/master/Functions/Get-IniContent.ps1 
This is useful to track when piping or when a function call an other function. 

 Are you against this?

**Comment by brianbunke** [comment]
I think this is fine. It's essential for private functions, which you're refactoring into, but I'm indifferent on public functions. Probably worthwhile, just because one public could call another (like what I've been doing with `Set-WikiInfo` up to now).

👍
