### ISSUE TITLE
Comment a page edit

### ISSUE THREAD

**Issue by lipkau** [brianbunke/ConfluencePS#22]
Allow to write a comment when using `Set-WikiPage`

**Comment by brianbunke** [comment]
Just to clarify, because I misread this the first time:

This is equivalent to the "What did you change?" field that would be viewable in the page history, right? Not adding a new comment at the bottom of an existing wiki page.

**Comment by lipkau** [comment]
Correct. I didn't find documentation on the API for this

**Comment by lipkau** [comment]
@brianbunke:
This appears to be something that the REST api does not support (yet).
I suggest adding a label to identify all issues that _might_ be implemented once REST supports it and close it.

**Comment by brianbunke** [comment]
Good plan. Closing this, and interested parties can periodically review https://github.com/brianbunke/ConfluencePS/labels/api%20limitation. Does Atlassian proactively send out notifications when they change the REST API, or do you just have to notice one day while browsing the documentation?
