### ISSUE TITLE
Structure of Label functions

### ISSUE THREAD

**Issue by lipkau** [brianbunke/ConfluencePS#23]
I personally find it confusing (or at least not aligned to best practices), that `New-WikiLabel` attaches a label to a page.
I would have believed that this functions creates a new label on confluence which I can use later on on pages.

I would propose to refactor the function so that:
```
# Gets all pages with label "important"
Get-WikiPage -Label "important"

# Adds a label to a page
$page | Add-WikiLabel -Label "label1","label2"

# Remove a label from a page
$page | Remove-WikiLabel -label "label1","label2"
```

**this would deprecate `New-WikiLabel`**

**Comment by lipkau** [comment]
this continues #15

**Comment by lipkau** [comment]
Optional (I think it's worth it):
```
# Removes all labels that are set and adds the new ones
$page | Set-WikiLabel -Label "theOnlyLabel"
```

**Comment by brianbunke** [comment]
We also discussed the following in chat:

```posh
# Default cmdlet behavior removes all labels from piped content
$page | Remove-WikiLabel
```

**Comment by lipkau** [comment]
but then again.... wouldn't that be kinda dangerous?
you forget to give a param and everything is gone?

maybe `-all`?

**Comment by brianbunke** [comment]
My opinion is that there should be default behavior, and that example is the most intuitive option. (Since this issue was opened with regards to the module being more intuitive 😛 )

As the author of many things that could be used destructively, my personal opinion is that I can't spend too much time worrying about people who use `Remove-Anything` without verifying their `Get-` results or utilizing `-WhatIf` and/or `-Confirm`.

**Comment by lipkau** [comment]
agreed 👍

**Comment by lipkau** [comment]
I am kinda annoyed by `Get-WikiLabel`.

## Situation
```
# returns all labels of each page in space PESTER
Get-WIkiPage -SpaceKey "PESTER" | Get-WikiLabel
```

I don't like that the snippet above returns a list of labels, but doesn't have any reference to what page was searched for the labels.
This is due to the refactoring of `Invoke-WikiMethod`. The casting to the object _Label_ happens, when there is no (clean) way to pass the _Page_ reference.

## Suggestion
I would prefer for the `Get-WikiPage` to already expand (call the API) the labels of the page and add a property _Labels_ (of type _Label_) to the _Page_ object.
```
# captures all pages in space PESTER
$pages = Get-WikiPage -SpaceKey PESTER

# prints all labels in space PESTER
$pages | Select Labels -unique 
```

_@brianbunke _

**Comment by lipkau** [comment]
I decided for a different approach than described above:

```
# returns all labels used in space PESTER
Get-WikiPage -SpaceKey PESTER | Get-WikiPageLabel | Select Labels -Unique
```

The output of `Get-WikiPageLabel` returns:
```
[ConfluencePS.ContentLabelSet]@{
  Page = [ConfluencePS.Page]
  Labels = [ConfluencePS.Label[]]
}
```

**Comment by lipkau** [comment]
## Renaming of existing function
currently the function to get the labels of a page is called `Get-WikiPageLabel`.

I am renaming this function, as once attachments/blogs are implemented, this function should be reused
