### ISSUE TITLE
Set labels with Set-WikiPage

### ISSUE THREAD

**Issue by lipkau** [brianbunke/ConfluencePS#24]
Should `Set-WikiPage` allow to set the labels of the page?

**Comment by lipkau** [comment]
extend #23 and #15

**Comment by brianbunke** [comment]
Yes. `-Label` will already be added to `Get-WikiPage`, so exposing it here as well totally makes sense.

**Comment by lipkau** [comment]
I tried it, but was unable to find a way to set labels with the same `PUT /rest/content/{contentId}` request.

Issue closed for now
