### ISSUE TITLE
Get-WikiPage limit outputs only 100 items

### ISSUE THREAD

**Issue by vzabauski** [brianbunke/ConfluencePS#3]
I'm using the latest version of module (cloned the repo today).
```
$pages = Get-WikiSpace -Name "KB" | Get-WikiPage -Limit 100 -Expand`

$pages.Title | Measure-Object -Line`

Lines Words Characters Property
----- ----- ---------- --------
  100                  
```

Okay, let's try to get all pages (I have about 107 pages).

```
$pages = Get-WikiSpace -Name "KB" | Get-WikiPage -Limit 300 -Expand

$pages.Title | Measure-Object -Line

Lines Words Characters Property
----- ----- ---------- --------
  100  
```
```
$pages = Get-WikiSpace -Name "KB" | Get-WikiPage -Limit 1000 -Expand

$pages.Title | Measure-Object -Line

Lines Words Characters Property
----- ----- ---------- --------
  100
```
Last 3 modules that Powershell got from Confluence
![1](https://cloud.githubusercontent.com/assets/17778043/20001000/35902072-a28b-11e6-87a3-cbd1d4ebdc2f.PNG)
The rest of modules that wasn't included though they are present in Confluence among other pages.
![2](https://cloud.githubusercontent.com/assets/17778043/20000841/8c4be0b4-a28a-11e6-816f-41636023cc87.PNG)

I'm not sure if this REST API issue or ConfluencePS module issue or maybe some kind of limit but I've thought you should know that. You can freely contact me if you need any details.

**Comment by brianbunke** [comment]
Welcome!

To the best of my knowledge, this is an API limitation. Using `-Expand`, I personally haven't seen a result >100. If you drop `-Expand`, you can at least return 500, if not more. (Side note: I've split off some of my automated pages into a dedicated space to help deal with this.)

To date, my workaround has been to use `Get-WikiPage` _without_ `-Expand`, find the Title/PageID I'm actually looking for, and then use PageID in a more targeted `-Expand` call.

So far, the only properties I include in `-Expand` are Version and Body. I plan to add more in the future, but probably not the near future. From your examples, you can grab (and filter by) Title without having to expand.

    # Your second example could just drop the -Expand altogether
    $pages = Get-WikiSpace -Name "KB" | Get-WikiPage -Limit 300
    $pages.Title | Measure-Object -Line

    Lines
    -------
    107-ish 😄

    # This works, but will take forever, and each page's Body will consume a lot of memory
    Get-WikiSpace -Name "KB" | Get-WikiPage -Limit 500 | Get-WikiPage -Expand
    # If possible, I'd encourage filtering as much as possible before using -Expand
    Get-WikiSpace -Name "KB" | Get-WikiPage -Limit 500 -Title 'reboot' | Get-WikiPage -Expand

Let me know if I'm lying. I hope the module ends up being useful for you!
