### ISSUE TITLE
How can I pass content to Confluence with non-UTF-8 characters?

### ISSUE THREAD

**Issue by vzabauski** [brianbunke/ConfluencePS#4]
Page body contains  some French characters, so I can't publish it on Confluence using New-WikiPage command. I know it's a json restriction but maybe there's a way to do this.
Example string: 

> From the Language drop down, select "Français (Canada)

I've tried to encode it using

```
$enc = [system.Text.Encoding]::UTF8
$encodedBytes = $enc.GetBytes($content)  
$decodedString = $enc.GetString($encodedBytes)  
```
but it didn't worked. Is there any workaround? Thanks.

**Comment by brianbunke** [comment]
Oh wow, great question. I'm not sure, will have to do some research.

**Comment by ScottWelker** [comment]
I believe you'll need to use the unicode character escape sequence, e.g. "**\u0nnn**" where _0nnn_ is the number corresponding to your desired character(s).

I grappled with something similar here: https://support.atlassian.com/servicedesk/customer/portal/14/CSP-185549

**Comment by vzabauski** [comment]
Thank you, Scott.
Sadly, I can't view the page you provided. But anyway, I understand what you mean.

**Comment by vzabauski** [comment]
I used the following function to remove unsupported characters. It's not a smooth decision but it works fine for me. At least, for now.
```

function Convert-DiacriticCharacters {
    param(
        [string]$inputString
    )
    [string]$formD = $inputString.Normalize(
            [System.text.NormalizationForm]::FormD
    )
    $stringBuilder = new-object System.Text.StringBuilder
    for ($i = 0; $i -lt $formD.Length; $i++){
        $unicodeCategory = [System.Globalization.CharUnicodeInfo]::GetUnicodeCategory($formD[$i])
        $nonSPacingMark = [System.Globalization.UnicodeCategory]::NonSpacingMark
        if($unicodeCategory -ne $nonSPacingMark){
            $stringBuilder.Append($formD[$i]) | out-null
        }
    }
    $stringBuilder.ToString().Normalize([System.text.NormalizationForm]::FormC)
}
```

**Comment by ScottWelker** [comment]
Sorry siabauski. I don't understand why my Confluence issue is not public. Anyway, happy to hear you've devised a functional work around.

**Comment by brianbunke** [comment]
Sounds good, I'll keep it in mind. Thanks for the info, both!
