### ISSUE TITLE
Invoke-WikiMethod splat error

### ISSUE THREAD

**Issue by brianbunke** [brianbunke/ConfluencePS#51]
Taking the 2.0 develop branch for a test drive.

https://github.com/brianbunke/ConfluencePS/blob/d7c9adfd9dec99f03a03097e020c5ca077ff236a/ConfluencePS/Private/Invoke-WikiMethod.ps1#L161

## Expected Behavior
No error expected.

## Current Behavior
`Invoke-WikiMethod : A parameter cannot be found that matches parameter name 'GetSystem.Collections.Hashtable'.`
`[...]`
`\Private\Invoke-WikiMethod.ps1:164 char:41`
`$result.results += (Invoke-WikiMethod @parameters)`

## Steps to Reproduce (for bugs)
```posh
Set-WikiInfo -BaseURi 'https://wiki.example.com' -PromptCredentials -PageSize 3
Get-WikiSpace
# Same error occurs above and below
Get-WikiPage
```

## Your Environment

* Operating System and PowerShell version: Win10 / 5.1.14393.1198
* ConfluencePS version: 2.0 `develop`

**Comment by lipkau** [comment]
How many pages should have been returned?

**Comment by brianbunke** [comment]
Sorry, I didn't copy the output. It gives me that error before I see the expected results.

In other words, it's actually working, just with some extra red text courtesy of `Invoke-WikiMethod`.

**Comment by lipkau** [comment]
This must defiantly be tested when we introduce Unit Tests
