### ISSUE TITLE
Add-WikiLabel parameters

### ISSUE THREAD

**Issue by brianbunke** [brianbunke/ConfluencePS#52]
Test driving the 2.0 `develop` branch:

I dislike `Add-WikiLabel` having both a `-Label` and a `-Labels` parameter. It's ambiguous, and requires the user to `Get-Help Add-WikiLabel -Parameter *` to discern the difference.

https://github.com/brianbunke/ConfluencePS/blob/d7c9adfd9dec99f03a03097e020c5ca077ff236a/ConfluencePS/Public/Add-WikiLabel.ps1

## Suggested Solution
Change `-Labels` to `-LabelSet`?

**Comment by lipkau** [comment]
Agreed.
I will look into it
