### ISSUE TITLE
Refactor Get-WikiPage

### ISSUE THREAD

**Issue by JohnLBevan** [brianbunke/ConfluencePS#53]
The code used to determine what columns are returned from Get-WikiResults has a lot of duplication.
Refactor to reduce duplication / make it more apparent what the differences are for each condition.

**Comment by brianbunke** [comment]
Hello, and welcome!

@lipkau has drastically refactored the module in the `develop` branch. It's currently waiting for me to go through everything, raise needed issues, fill in any missing docs, and release as new version `2.0`. Sorry this isn't immediately obvious right now 😞...hopefully it's a very short term problem before the release happens.

As we're basically working off of `develop` and raising issues against it at this point, I'm going to close this out. Happy to answer any follow-up questions, though!

**Comment by JohnLBevan** [comment]
Ah no worries; thanks for the note.
I'll work off the dev branch for #50 .

Thanks again.
