### ISSUE TITLE
Vanilla Get-WikiPage

### ISSUE THREAD

**Issue by brianbunke** [brianbunke/ConfluencePS#58]
Applies to branch `develop` (`2.0`) as of 2017/06/18.

## Expected Behavior
`Get-WikiPage` returns all pages (or, once pagination is fixed, the correct page size).

## Current Behavior
`Get-WikiPage` prompts for `-PageID` (a required parameter in the default parameter set), and fails when one is not provided.

## Steps to Reproduce (for bugs)
1. `Get-WikiPage`

## Possible Solution
I do not yet have a technical solution to propose. This issue is primarily intended to be a discussion.

## Context
I expect `Get-WikiSpace` and `Get-WikiPage`, with no parameters, to be fairly common "discovery commands" from new users. I'm using them to wrap my head around the changes in the `develop` branch, so it's a little weird to me that `Get-WikiPage` is erroring out.

I've labeled this "Milestone `v2.0`," but I just want us to get on the same page before that ships. Fixing this isn't absolutely required if we agree on something else.

If we agree that these commands should work in "vanilla" mode (no other specified parameters), this usage needs to be added to the integration test suite.

**Comment by lipkau** [comment]
I believe, that `Get-WikiPage` without *any* parameter is dangerous.
I know 3 productive Confluence server. On all of them:
1. the result would be no help at all.
2. it would take forever to complete.

We can do it. No problem.
But I would prefer for the user to have a bit more trouble to get *all* pages from *all* spaces:
```
Get-WikiSpace | Get-WikiPage
```

**Comment by brianbunke** [comment]
Yeah, I'm fine with that. A technical question:

With pagination working properly, I assume that Get-WikiPage would only fetch x (25?) pages, and therefore be less "dangerous" on an established instance. Is that correct?

**Comment by lipkau** [comment]
No

**Comment by lipkau** [comment]
can this be closed?
