### ISSUE TITLE
Further cmdlets

### ISSUE THREAD

**Issue by lipkau** [brianbunke/ConfluencePS#9]
Hi.

I am very exited to have found your repo.
I wrote something similar a long time ago (using the SOAP api) and was feeling lazy migrating to the REST api; especial now, that a lot of methods are not yet supported by the REST api - or I am unsure how to support both (REST & XMLRPC) simultaneously (my company is still on 9.1.x - where REST is still seriously lacking).

In case you want to have a look, my repo is https://github.com/lipkau/PsConfluence

I am planing on submitting some PRs to this repo 👍 

BR
Oliver

**Comment by brianbunke** [comment]
Welcome! The more, the merrier 😄

Looking forward to seeing some PRs; definitely feel free to submit what you're working on. I know there are large areas of the API that haven't been implemented.

Let me know if I can save you some time by answering any questions!
